name: BloedBond
favicon: null
layout_spectrum: 0.89381
typography_spectrum: 0.35891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4d3ce'
    - '#11161c'
    - '#80999e'
    - '#2f343a'
    - '#464f4d'
  brandStrength: 0.1875
  lightness: 0.3167278873734176
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
