name: BloedBond
favicon: null
layout_spectrum: 0.53036
typography_spectrum: 0.35891
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6fafb'
    - '#226553'
    - '#3c8c47'
    - '#6fbf42'
    - '#bcdc94'
  brandStrength: 0.1875
  lightness: 0.3167278873734176
  saturation: 0.6875
  rhythmicContrast: 0.6175950057804585
purpose: []
